### ISSUE TITLE
OBS Scene Switch issue

### ISSUE THREAD

**Issue by Onewingseraphim** [Pantotone/YAWO4YARG#3]
I know it's experimental but just in case you weren't aware.

It works really well as is however I'm having an issue where if I manually change back to my MAIN scene during a song playback it will go back to my YARG scene after the song ends instead of staying on my MAIN scene.

I have YARG set to during song play and MAIN set to when song not playing.

Edit: Not sure why but today when I tried this it didn't happen again so must've been a fluke or maybe only under certain conditions (I have no idea)

**Comment by Pantotone** [comment]
Thanks for reporting!

I couldn't reproduce the bug on my end, but I think I may know what could be causing this.
Just committed a bug fix, hopefully it fixes the problem.

If it happens again, feel free to reopen the issue/create a new one.
